---
- name: Install default Apache web Server
  hosts: all

  tasks: 
  - name: Install Apache WebServer
    apt: name=apache2 state=latest

  - name: Start Apache and Enable and it on the every boot
    service: name=apache2 state=started enabled=yes
 

